import { useEffect, useRef } from "react";

const CodeCalendar = () => {
  const calendarRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    if (!calendarRef.current) return;
    
    const container = calendarRef.current;
    const days = 365;
    const levels = [0, 1, 2, 3, 4]; // Activity levels
    
    // Clear existing calendar
    container.innerHTML = '';
    
    for (let i = 0; i < days; i++) {
      const day = document.createElement('div');
      day.className = 'calendar-day';
      
      // Random activity level
      const level = levels[Math.floor(Math.random() * levels.length)];
      day.classList.add(`level-${level}`);
      
      container.appendChild(day);
    }
  }, []);

  return (
    <div className="bg-card p-6 rounded-lg">
      <div className="flex justify-between mb-2 text-sm text-gray-400">
        <span>Mar</span>
        <span>Apr</span>
        <span>May</span>
        <span>Jun</span>
        <span>Jul</span>
        <span>Aug</span>
        <span>Sep</span>
        <span>Oct</span>
        <span>Nov</span>
        <span>Dec</span>
        <span>Jan</span>
        <span>Feb</span>
        <span>Mar</span>
      </div>
      
      <div ref={calendarRef} className="flex flex-wrap justify-center">
        {/* Calendar will be generated by JS */}
      </div>
      
      <div className="flex justify-between mt-4 text-sm text-gray-400">
        <div>415 Activities in the last year</div>
        <div className="flex items-center gap-1">
          <span>Less</span>
          <div className="flex">
            <div className="calendar-day level-0"></div>
            <div className="calendar-day level-1"></div>
            <div className="calendar-day level-2"></div>
            <div className="calendar-day level-3"></div>
            <div className="calendar-day level-4"></div>
          </div>
          <span>More</span>
        </div>
      </div>
    </div>
  );
};

export default CodeCalendar;
